// <auto-generated />
using System;
using ASRE.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASRE.PatientApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASRE.DataLayer.Models.Activation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Activations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("350fda9b-d8e0-4df4-ad3f-9a374c9e0801"),
                            Name = "true"
                        },
                        new
                        {
                            Id = new Guid("920b297b-8827-45ca-9d9b-f3eea9f2fcb4"),
                            Name = "false"
                        });
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38f4e1cc-440c-4e10-94c9-af1db3364f07"),
                            Name = "unknown"
                        },
                        new
                        {
                            Id = new Guid("7c610b7c-9a23-4f54-bf1f-e9d5d02b6b5d"),
                            Name = "male"
                        },
                        new
                        {
                            Id = new Guid("ecb9f689-9427-4e27-8c23-2ac2c3e3d0a5"),
                            Name = "female"
                        },
                        new
                        {
                            Id = new Guid("e97c5b5d-484c-43e9-8850-d65c57579875"),
                            Name = "other"
                        });
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActivationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("GenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Use")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ActivationId");

                    b.HasIndex("GenderId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.PatientGivenName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientGivenNames");
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.Patient", b =>
                {
                    b.HasOne("ASRE.DataLayer.Models.Activation", "Activation")
                        .WithMany("Patients")
                        .HasForeignKey("ActivationId");

                    b.HasOne("ASRE.DataLayer.Models.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("GenderId");

                    b.Navigation("Activation");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.PatientGivenName", b =>
                {
                    b.HasOne("ASRE.DataLayer.Models.Patient", "Patient")
                        .WithMany("PatientGivenNames")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.Activation", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.Gender", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ASRE.DataLayer.Models.Patient", b =>
                {
                    b.Navigation("PatientGivenNames");
                });
#pragma warning restore 612, 618
        }
    }
}
